comment:
  image:
    repository: dzhbanov11/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: dzhbanov11/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: dzhbanov11/ui
    tag: latest
  service:
    externalPort: 9292
