kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 6VFzpVdDp0IDLUT6rrEOtZjaPPOa+lu1OWgdpFuEDvc=
      - identity: {}
